apiVersion: v1
kind: Service
metadata:
  name: matching-engine
  namespace: oms
  labels:
    app: matching-engine
spec:
  selector:
    app: matching-engine
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
