apiVersion: v1
kind: Service
metadata:
  name: risk-engine
  namespace: oms
  labels:
    app: risk-engine
spec:
  selector:
    app: risk-engine
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
